# Generated by Django 3.2.5 on 2021-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(null=True, max_length=25),
        ),
    ]
